#pragma once

#define _GRAPH_WIDTH_ 1140
#define _GRAPH_HEIGHT_ 720
#define _GRID_LENGTH_ 60
#define _GRID_NUM_IN_WIDTH_ 18
#define _GRID_NUM_IN_HEIGHT_ 11
#define _NUM_OF_OBSTALCES_ 6
#define _NICHT_ESIST_ENCIA_ 0
#define _BOMB_RELEASE_INTERVAL_ 5500
#define _ENEMY_1_GENERATION_INTERVAL_ 3300
#define _ENEMY_2_GENERATION_INTERVAL_ 8800
